---
server:
  applicationConnectors:
    - type: http
      port: 10001
  adminConnectors:
    - type: http
      port: 10002

simpleEmailService:
  fromEmailAddress: linus.jahn@searchmetrics.com
  replyToEmailAddress: linus.jahn@searchmetrics.com
  printOutgoingEmails: true
  s3BucketName: simple-email-service-bucket

#logging:
#  level: DEBUG